spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Sarthak2000@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka





